name:                kernmantle
version:             0.1.0.0
github:              "YPares/kernmantle"
license:             BSD3
author:              "Yves Parès"
maintainer:          "yves.pares@gmail.com"
copyright:           "2019 Yves Parès"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Composing Applicatives, Monads, Comonads and Arrows into Arrows
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YPares/kernmantle#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors
- profunctors
- comonad
- vinyl >= 0.11
- transformers
- safe-exceptions

library:
  source-dirs: src

executables:
  ex1:
    main: examples/Ex1.hs
    dependencies:
      - kernmantle
  exBuilder:
    main: examples/ExBuilder.hs
    dependencies:
      - kernmantle
  exCli:
    main: examples/ExCli.hs
    dependencies:
      - kernmantle
      - optparse-applicative
      - profunctors
      - bytestring
  exCaching:
    main: examples/ExCaching.hs
    dependencies:
      - kernmantle
      - cas-hashable
      - cas-store
      - optparse-applicative
      - profunctors
      - bytestring
      - path
      - path-io
