name:                kernmantle-caching
version:             0.1.0.0
github:              "YPares/kernmantle"
license:             BSD3
author:              "Yves Parès"
maintainer:          "yves.pares@gmail.com"
copyright:           "2019 Yves Parès"

# Metadata used when publishing your package
synopsis:            Cache parts of a Kernmantle pipeline via cas-store
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YPares/kernmantle#readme>

dependencies:
- base >= 4.7 && < 5
- kernmantle
- path
- path-io
- store
- cas-hashable
- cas-store
- monad-control
- exceptions

library:
  source-dirs: src

executables:
  exCaching:
    main: examples/ExCaching.hs
    dependencies:
      - kernmantle
      - kernmantle-caching
      - optparse-applicative
      - transformers
      - profunctors
      - bytestring
  exCachingAlt:
    main: examples/ExCachingAlt.hs
    dependencies:
      - kernmantle
      - optparse-applicative
      - containers
      - bytestring
      - profunctors
